### ISSUE TITLE
Hi Christopher, 

### ISSUE THREAD

**Issue by ckarthikin** [boumenot/Grobid.NET#1]
Hi Christopher, 

Thanks for sharing the great code Grobid.NET. Really it would be grateful on my PG project. I have just build the code, it shows it seems the dll assemblies are missing, can you plz guide me, how to get the required dll.

Best Regards,
karthikc

**Comment by boumenot** [comment]
Thank you for opening an issue!  

My best guess is that all of bits didn't get pulled down from NuGet and MyGet.  I have _private_ builds of a few assemblies, and they are currently stored in MyGet.

A version of pdftoxml is also stored in MyGet with all of the necessary libraries to run out-of-the-box.  You will need to set an environment variable to tell Grobid.NET where these this is located.

```cmd
PDFTOXMLEXE=c:\...\path\to\pdf2xml.exe
```

I run the build/test on AppVeyor, so all of the bits should be included because the latest build is green.  You should be able to re-create the build/test by executing the same steps as it.

```cmd
build.cmd BuildApp
build.cmd UnitTests
```

I should add all of this to the README.  👍

**Comment by ckarthikin** [comment]
Hi Christopher,

Thank you so much for your reply. I have followed the steps as explained. everything works fine...Fantastic...i have done UnitTests also..its working fine...only thing i want to know where the output file get created?. Dorry it may be silly question but  i couldnt able to find the location.

Best Regards,
karthikc

**Comment by ckarthikin** [comment]
Hi, I digged into deep and got the results..thanks..

Is it possible extract the fulltextparser output then what is need to be changed in the below code.
var parser = this.engine.getHeaderParser();            
var biblioItem = new BiblioItem(this.lexicon);
var result = (string)parser.processing2(fileName, false, biblioItem).getLeft();

Best Regards,
karthikc
